### ISSUE TITLE
valgrind shows leaks

### ISSUE THREAD

**Issue by freevryheid** [fortran-lang/test-drive#25]
for tests developed using this, which complicates tracking down memory issues when testing code.

**Comment by awvwgk** [comment]
There are three memory leaks flagged in valgrind with GFortran, which all come from automatic LHS allocation.

I believe this is something we cannot fix on our side with test-drive, rather this seems to be caused by the way the compiler implements the automatic LHS allocation, but replacing with sourced allocation doesn't fix the issue. Maybe this is be due to the fact that we return the value from a function rather using a subroutine, if that should be the case, there would be not much we can do about it without rewriting the way test-drive declares its tests.

https://github.com/fortran-lang/test-drive/blob/97b848bd4299133cf5f99c84371e4fa5445445e7/src/testdrive.F90#L782

````
==35172==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==35172==    by 0x11E8FC: __testdrive_MOD_new_unittest (testdrive.F90:782)
==35172==    by 0x1107D2: __test_check_MOD_collect_check (in /home/sehlert/projects/git/test-drive/build/gfortran_E167FD2A985B468F/test/test-drive-test)
==35172==    by 0x128B32: __testdrive_MOD_run_testsuite (testdrive.F90:371)
==35172==    by 0x10A4A8: MAIN__ (main.f90:62)
==35172==    by 0x10A5B9: main (main.f90:18)
````

---

https://github.com/fortran-lang/test-drive/blob/97b848bd4299133cf5f99c84371e4fa5445445e7/src/testdrive.F90#L801


````
==35172==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==35172==    by 0x11E7BD: __testdrive_MOD_new_testsuite (testdrive.F90:801)
==35172==    by 0x10966B: MAIN__ (main.f90:34)
==35172==    by 0x10A5B9: main (main.f90:18)
````

---

https://github.com/fortran-lang/test-drive/blob/97b848bd4299133cf5f99c84371e4fa5445445e7/test/main.f90#L31-L34


````
==35172==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==35172==    by 0x109822: MAIN__ (main.f90:34)
==35172==    by 0x10A5B9: main (main.f90:18)
````
