### ISSUE TITLE
Simplify `check` and `return` handling

### ISSUE THREAD

**Issue by certik** [fortran-lang/test-drive#3]
Why not simplify:
```fortran
            call check(error, all(input == expected))
            if (allocated(error)) return
```
to:
```fortran
            if (check(error, all(input == expected))) return
```
Beyond that, the only other way to simplify is using macros, but I like that this is very usable without macros.

**Comment by awvwgk** [comment]
Using subroutines instead of functions for test-drive was a deliberate choice, but I'm open to discuss and reevaluate this decision.

The optimal unit test should not require a `return` statement at all. Instead we should encourage aiming for smaller tests, the best in my opinion is to have a unit test like

```f90
subroutine test_something(error)
  type(error_type), allocatable, intent(out) :: error
  ! ... calculate something
  call check(error, actual, expected)
end subroutine test_something
```

In this scenario there is no need for a return statement at all. We get one test which tests exactly one thing.

In reality, of course, things are more complicated and one might need several `check` calls in one subroutine, especially if IO resources are involved, which have to be closed again. An example for such case would be [`test_stdlib_bitset_64`](https://github.com/fortran-lang/stdlib/blob/58b84677d4aa6132658509539718db42ebbc4e8b/src/tests/bitsets/test_stdlib_bitset_64.f90#L168-L185). In this case one would end up with constructs like `if (.not.check(error, ...)) then` to continue testing, which I find unintuitive.

Maybe Brad @everythingfunctional can comment on this issue and his choice for vegetables, which is based on a somewhat similar logic to organize unit tests.
